name = "ABMPredictionMarkets"
uuid = "f93c7831-927e-41b2-8014-b29c2a7d30aa"
authors = ["itsdfish <itsdfish@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
